# Public series selected from the broader research catalogue because they
# add distinct macro, property, credit, global or yield-curve information to
# this tracker.  Existing tracker series are deliberately not duplicated.
RBA_ENHANCEMENT_SERIES = {
    "cpi_nontradables_yoy": {
        "table": "cpi_history", "series_id": "GCPINTIYP", "label": "Non-tradables CPI inflation",
        "unit": "% y/y", "frequency": "quarterly", "release_lag_days": 30,
        "definition": "Annual change in the non-tradables component of the Australian CPI.",
        "usage": "Use as a diagnostic for domestically generated and services-heavy inflation persistence.",
        "housing_market_link": "Persistent domestic inflation can delay rate relief and keep mortgage servicing costs elevated.",
    },
    "housing_cpi_yoy": {
        "table": "housing_cpi_history", "series_id": "GCPIHOYP", "label": "CPI housing component inflation",
        "unit": "% y/y", "frequency": "quarterly", "release_lag_days": 30,
        "definition": "Annual change in the CPI housing group, including rents, new dwelling costs and utilities.",
        "usage": "Track housing-related consumer-price pressure; do not treat it as a dwelling-price index.",
        "housing_market_link": "Separates housing consumption costs from changes in established-home market values.",
    },
    "consumer_inflation_expectations_1y": {
        "table": "inflation_expectations", "series_id": "GCONEXP", "label": "Consumer inflation expectations (1 year)",
        "unit": "%", "frequency": "monthly", "release_lag_days": 20,
        "definition": "Survey measure of consumers' expected inflation over the coming year.",
        "usage": "Use as a noisy but timely indicator of household inflation psychology.",
        "housing_market_link": "Expectations can affect wage demands, spending and the persistence of restrictive mortgage rates.",
    },
    "market_economist_inflation_expectations_1y": {
        "table": "inflation_expectations", "series_id": "GMAREXPY", "label": "Market economists' inflation expectations (1 year)",
        "unit": "%", "frequency": "quarterly", "release_lag_days": 30,
        "definition": "Survey expectation of CPI inflation from market economists at a one-year horizon.",
        "usage": "Compare professional expectations with consumer expectations and market pricing.",
        "housing_market_link": "Affects the expected policy path and therefore fixed and variable housing finance conditions.",
    },
    "market_economist_inflation_expectations_2y": {
        "table": "inflation_expectations", "series_id": "GMAREXPYY", "label": "Market economists' inflation expectations (2 years)",
        "unit": "%", "frequency": "quarterly", "release_lag_days": 30,
        "definition": "Survey expectation of CPI inflation from market economists at a two-year horizon.",
        "usage": "Assess whether inflation expectations are converging toward the RBA target over the policy horizon.",
        "housing_market_link": "Anchored medium-term expectations support eventual mortgage-rate normalisation.",
    },
    "breakeven_inflation_10y": {
        "table": "inflation_expectations", "series_id": "GBONYLD", "label": "10-year bond breakeven inflation",
        "unit": "%", "frequency": "monthly", "release_lag_days": 10,
        "definition": "RBA-published difference between nominal and indexed Australian government bond yields at a long horizon.",
        "usage": "Use as a market-based inflation-compensation proxy, not a pure expectation; liquidity and risk premia matter.",
        "housing_market_link": "Long-run inflation compensation influences nominal bond yields and fixed mortgage pricing.",
    },
    "wage_growth_total_yoy": {
        "table": "labour_costs_productivity", "series_id": "GWPIYP", "label": "Wage Price Index growth",
        "unit": "% y/y", "frequency": "quarterly", "release_lag_days": 50,
        "definition": "Annual growth in the Australian Wage Price Index across all sectors.",
        "usage": "Use as the broad fixed-job wage-pressure measure alongside sector-specific WPI series.",
        "housing_market_link": "Wage growth supports borrowing capacity but may prolong inflation and high mortgage rates.",
    },
    "unit_labour_costs_yoy": {
        "table": "labour_costs_productivity", "series_id": "GNFULCYP", "label": "Nominal unit labour cost growth",
        "unit": "% y/y", "frequency": "quarterly", "release_lag_days": 70,
        "definition": "Annual growth in nominal non-farm unit labour costs.",
        "usage": "Assess wage pressure relative to productivity rather than wages in isolation.",
        "housing_market_link": "Persistent labour-cost pressure can slow disinflation and delay reductions in housing finance costs.",
    },
    "labour_productivity_yoy": {
        "table": "labour_costs_productivity", "series_id": "GNFPROSQP", "label": "Labour productivity growth",
        "unit": "% y/y", "frequency": "quarterly", "release_lag_days": 70,
        "definition": "Annual growth in non-farm GDP per hour worked.",
        "usage": "Interpret whether wage growth is inflationary or supported by productivity gains.",
        "housing_market_link": "Stronger productivity can support real incomes and lower inflation pressure over time.",
    },
    "real_gdp_growth_yoy": {
        "table": "gdp_income", "series_id": "GGDPCVGDPY", "label": "Real GDP growth",
        "unit": "% y/y", "frequency": "quarterly", "release_lag_days": 70,
        "definition": "Annual growth in chain-volume gross domestic product.",
        "usage": "Track aggregate economic momentum and recession risk.",
        "housing_market_link": "Growth affects employment, household income, credit demand and arrears risk.",
    },
    "real_gdp_per_capita_growth_yoy": {
        "table": "gdp_income", "series_id": "GGDPCVGDPFY", "label": "Real GDP per capita growth",
        "unit": "% y/y", "frequency": "quarterly", "release_lag_days": 70,
        "definition": "Annual growth in real GDP per person.",
        "usage": "Distinguish population-led aggregate growth from changes in average economic activity.",
        "housing_market_link": "Per-capita weakness can constrain household purchasing power even when population growth supports dwelling demand.",
    },
    "household_consumption_growth_yoy": {
        "table": "demand_income", "series_id": "GGDPECCVPSHY", "label": "Household consumption growth",
        "unit": "% y/y", "frequency": "quarterly", "release_lag_days": 70,
        "definition": "Annual growth in real household final consumption expenditure.",
        "usage": "Gauge household demand and monetary-policy transmission.",
        "housing_market_link": "Weak consumption can reveal mortgage-rate pressure before it appears in housing turnover or arrears.",
    },
    "dwelling_investment_growth_yoy": {
        "table": "demand_income", "series_id": "GGDPECCVPSDY", "label": "Dwelling investment growth",
        "unit": "% y/y", "frequency": "quarterly", "release_lag_days": 70,
        "definition": "Annual growth in real private dwelling investment.",
        "usage": "Track construction activity actually entering GDP, complementing the approvals pipeline.",
        "housing_market_link": "Links approvals and finance to delivered residential construction activity.",
    },
    "consumer_sentiment": {
        "table": "monthly_activity", "series_id": "GICWMICS", "label": "Consumer sentiment index",
        "unit": "index", "frequency": "monthly", "release_lag_days": 15,
        "definition": "Westpac-Melbourne Institute consumer sentiment index republished by the RBA.",
        "usage": "Use as a timely soft indicator; survey volatility means it should not stand alone.",
        "housing_market_link": "Confidence affects buyer enquiry, major purchases and willingness to take on housing debt.",
    },
    "business_conditions": {
        "table": "monthly_activity", "series_id": "GICNBC", "label": "NAB business conditions index",
        "unit": "index", "frequency": "monthly", "release_lag_days": 20,
        "definition": "NAB business conditions index republished by the RBA.",
        "usage": "Use as a timely indicator of trading, profitability and employment conditions.",
        "housing_market_link": "Business strength supports labour demand and household income, indirectly supporting housing demand.",
    },
    "employment_growth_yoy": {
        "table": "labour_force_history", "series_id": "GLFSEPTSYP", "label": "Employment growth",
        "unit": "% y/y", "frequency": "monthly", "release_lag_days": 20,
        "definition": "Annual growth in seasonally adjusted employed persons.",
        "usage": "Read alongside unemployment and participation to assess labour-demand momentum.",
        "housing_market_link": "Employment growth supports household formation, borrowing capacity and mortgage serviceability.",
    },
    "participation_rate": {
        "table": "labour_force_history", "series_id": "GLFSPRSA", "label": "Labour-force participation rate",
        "unit": "%", "frequency": "monthly", "release_lag_days": 20,
        "definition": "Seasonally adjusted labour-force participation rate.",
        "usage": "Interpret changes in unemployment and labour supply more completely.",
        "housing_market_link": "Participation affects aggregate household income and the meaning of unemployment movements.",
    },
    "housing_credit_growth_yoy": {
        "table": "financial_aggregates_growth", "series_id": "DGFACH12", "label": "Housing credit growth",
        "unit": "% y/y", "frequency": "monthly", "release_lag_days": 35,
        "definition": "Annual growth in credit outstanding for housing.",
        "usage": "Track the stock of housing credit rather than new lending flows.",
        "housing_market_link": "Accelerating credit growth often accompanies stronger housing demand and leverage.",
    },
    "owner_occupier_credit_growth_yoy": {
        "table": "financial_aggregates_growth", "series_id": "DGFACOH12", "label": "Owner-occupier housing credit growth",
        "unit": "% y/y", "frequency": "monthly", "release_lag_days": 35,
        "definition": "Annual growth in owner-occupier housing credit outstanding.",
        "usage": "Separate owner-occupier leverage from investor credit dynamics.",
        "housing_market_link": "Shows whether credit expansion is being driven by households buying homes to occupy.",
    },
    "investor_credit_growth_yoy": {
        "table": "financial_aggregates_growth", "series_id": "DGFACIH12", "label": "Investor housing credit growth",
        "unit": "% y/y", "frequency": "monthly", "release_lag_days": 35,
        "definition": "Annual growth in investor housing credit outstanding.",
        "usage": "Track investor leverage separately from owner-occupier borrowing.",
        "housing_market_link": "Investor credit can amplify price cycles and affect rental supply.",
    },
    "housing_lending_rate_owner_occupier_new": {
        "table": "housing_lending_rates", "series_id": "FLRHOFTA", "label": "Owner-occupier housing lending rate — new loans",
        "unit": "%", "frequency": "monthly", "release_lag_days": 35,
        "definition": "Average interest rate on new owner-occupier housing loans funded in the month.",
        "usage": "Compare the marginal borrowing rate with rates paid on the outstanding loan book.",
        "housing_market_link": "A direct measure of current financing terms faced by new owner-occupier borrowers.",
    },
    "housing_lending_rate_investor_outstanding": {
        "table": "housing_lending_rates", "series_id": "FLRHIOTA", "label": "Investor housing lending rate — outstanding loans",
        "unit": "%", "frequency": "monthly", "release_lag_days": 35,
        "definition": "Average interest rate on outstanding investor housing loans.",
        "usage": "Track debt-service pressure across the existing investor loan book.",
        "housing_market_link": "Higher investor servicing costs affect cash flow, rents and decisions to hold or sell property.",
    },
    "housing_lending_rate_investor_new": {
        "table": "housing_lending_rates", "series_id": "FLRHIFTA", "label": "Investor housing lending rate — new loans",
        "unit": "%", "frequency": "monthly", "release_lag_days": 35,
        "definition": "Average interest rate on new investor housing loans funded in the month.",
        "usage": "Measure current marginal financing conditions for property investors.",
        "housing_market_link": "Influences investor demand, required rental yields and new rental supply.",
    },
    "trade_weighted_aud": {
        "table": "exchange_rates", "series_id": "FXRTWI", "label": "Australian dollar trade-weighted index",
        "unit": "index", "frequency": "daily (monthly last)", "release_lag_days": 2, "monthly_last": True,
        "definition": "RBA trade-weighted index of the Australian dollar, sampled at the last available observation each month.",
        "usage": "Assess broad exchange-rate transmission to imported inflation and financial conditions.",
        "housing_market_link": "Exchange-rate moves can alter inflation, policy expectations and foreign purchasing power.",
    },
    "aud_usd": {
        "table": "exchange_rates", "series_id": "FXRUSD", "label": "AUD/USD exchange rate",
        "unit": "USD per AUD", "frequency": "daily (monthly last)", "release_lag_days": 2, "monthly_last": True,
        "definition": "US dollars per Australian dollar, sampled at the last available observation each month.",
        "usage": "Track a major channel for imported inflation and global risk transmission.",
        "housing_market_link": "Affects tradable inflation, interest-rate expectations and offshore investor purchasing power.",
    },
    "commodity_price_index_aud": {
        "table": "commodity_prices", "series_id": "GRCPAIAD", "label": "RBA commodity price index (AUD)",
        "unit": "index", "frequency": "monthly", "release_lag_days": 5,
        "definition": "RBA index of commodity prices relevant to Australian exports, expressed in Australian dollars.",
        "usage": "Track terms-of-trade and national-income impulses from commodity markets.",
        "housing_market_link": "Commodity income affects employment, migration and housing demand in resource-exposed regions.",
    },
    "corporate_bbb_yield_5y": {
        "table": "corporate_bond_yields", "series_id": "FNFYBBB5M", "label": "Australian non-financial BBB corporate yield (5 year)",
        "unit": "%", "frequency": "monthly", "release_lag_days": 15,
        "definition": "Estimated five-year yield for Australian non-financial BBB-rated corporate bonds.",
        "usage": "Use as a broader financial-conditions measure; it is a yield, not a credit spread.",
        "housing_market_link": "Tighter corporate financing conditions can weaken employment, development finance and risk appetite.",
    },
    "au_zero_yield_2y": {"table": "zero_coupon_yields", "series_id": "FZCY200D", "label": "Australian zero-coupon yield (2 year)", "unit": "%", "frequency": "daily (monthly last)", "release_lag_days": 5, "monthly_last": True},
    "au_zero_yield_5y": {"table": "zero_coupon_yields", "series_id": "FZCY500D", "label": "Australian zero-coupon yield (5 year)", "unit": "%", "frequency": "daily (monthly last)", "release_lag_days": 5, "monthly_last": True},
    "au_zero_yield_8y": {"table": "zero_coupon_yields", "series_id": "FZCY800D", "label": "Australian zero-coupon yield (8 year)", "unit": "%", "frequency": "daily (monthly last)", "release_lag_days": 5, "monthly_last": True},
    "au_zero_yield_9y": {"table": "zero_coupon_yields", "series_id": "FZCY900D", "label": "Australian zero-coupon yield (9 year)", "unit": "%", "frequency": "daily (monthly last)", "release_lag_days": 5, "monthly_last": True},
    "au_zero_yield_10y": {"table": "zero_coupon_yields", "series_id": "FZCY1000D", "label": "Australian zero-coupon yield (10 year)", "unit": "%", "frequency": "daily (monthly last)", "release_lag_days": 5, "monthly_last": True},
}
RBA_SOURCE_NAMES = {
    "cpi_history": "RBA Statistical Table G1 (ABS CPI)",
    "housing_cpi_history": "RBA Statistical Table G2 (ABS CPI expenditure groups)",
    "inflation_expectations": "RBA Statistical Table G3 (Inflation Expectations)",
    "labour_costs_productivity": "RBA Statistical Table H4 (Labour Costs and Productivity)",
    "gdp_income": "RBA Statistical Table H1 (GDP and Income)",
    "demand_income": "RBA Statistical Table H2 (Expenditure and Income)",
    "monthly_activity": "RBA Statistical Table H3 (Activity and Labour Indicators)",
    "labour_force_history": "RBA Statistical Table H5 (ABS Labour Force)",
    "financial_aggregates_growth": "RBA Statistical Table D1 (Growth in Financial Aggregates)",
    "housing_lending_rates": "RBA Statistical Table F6 (Housing Lending Rates)",
    "exchange_rates": "RBA Statistical Table F11.1 (Exchange Rates)",
    "commodity_prices": "RBA Statistical Table I2 (Commodity Prices)",
    "corporate_bond_yields": "RBA Statistical Table F3 (Aggregate Measures of Australian Corporate Bond Yields)",
    "zero_coupon_yields": "RBA Statistical Table F17 (Indicative Mid Rates of Australian Government Securities)",
}
